# Generated by Django 3.2.25 on 2024-04-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hesam', '0003_auto_20240418_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={},
        ),
    ]
