# Generated by Django 3.2.25 on 2024-04-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hesam', '0004_alter_contacts_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
